[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra --strict-markers --disable-warnings --maxfail=1 --cov=."
testpaths = [
  "tests"
]
markers = [
  "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]

